include_configs:
  - "full_1k_perfect.yaml"

name: 'shapenet-perfect1k/main_phase1'
model: full_net_phase1

load_pretrained: null

supervision:
  vox_normal:
    weight: 25.0

structure_schedule:
  start_step: 5000
  end_step: 20000
